
How to do this so that we actually make predictions for, say, nulls or 0's???
see: http://www.quuxlabs.com/blog/2010/09/matrix-factorization-a-simple-tutorial-and-implementation-in-python/


SKLEARN does matrix FACTORISATION but NOT matrix COMPLETION: http://stackoverflow.com/questions/34834801/nmf-sparse-matrix-analysis-using-sklearn?rq=1


movie ratings: How you could code it by hand: http://bugra.github.io/work/notes/2014-04-19/alternating-least-squares-method-for-collaborative-filtering/

Python: look at https://github.com/marinkaz/nimfa


scikit: basic FACTORISATION, doesn't do COMPLETION

In [41]:
import numpy as np
from sklearn.decomposition import NMF , ProjectedGradientNMF
R = [
     [5,3,0,5],
     [4,0,0,1],
     [1,1,4,5],
     [1,0,0,4],
     [0,1,5,4],
    ]
R = np.array(R) 
#R = normalize(R)
nmf = ProjectedGradientNMF(n_components=3)
#nmf = NMF(n_components=3, init='random')
W = nmf.fit_transform(R);
H = nmf.components_;
nR = np.dot(W,H)
print np.round(nR,1)

[[ 5.2  2.1  0.   5.2]
 [ 3.8  1.   0.   0.8]
 [ 1.   1.2  4.   5. ]
 [ 0.8  0.9  0.   3.8]
 [ 0.   0.8  5.   4. ]]


Example that masks values to test error

http://codereview.stackexchange.com/questions/96725/imputing-values-with-non-negative-matrix-factorization

In [18]:
from pandas import DataFrame
import numpy as np
from sklearn.decomposition import ProjectedGradientNMF

# Example data matrix X
nrows, ncols = 200, 150
toy_vals = np.random.random(nrows*ncols).reshape((nrows, ncols))
toy_vals[toy_vals < 0.9] = np.nan
X = DataFrame(toy_vals, index=range(nrows), columns=range(ncols))

# Hiding values to test imputation
X_imputed = X.copy()
msk = (X.values + np.random.randn(*X.shape) - X.values) < 0.8
X_imputed.values[~msk] = 0

# Initializing model
nmf_model = ProjectedGradientNMF(n_components=5)
nmf_model.fit(X_imputed.values)

# iterate model
while nmf_model.reconstruction_err_**2 > 10:
    W = nmf_model.fit_transform(X_imputed.values)
    X_imputed.values[~msk] = W.dot(nmf_model.components_)[~msk]
    print nmf_model.reconstruction_err_

/Users/Cam/anaconda/lib/python2.7/site-packages/sklearn/decomposition/nmf.py:532: UserWarning: Iteration limit reached during fit. Solving for W exactly.
  warnings.warn("Iteration limit reached during fit. Solving for W exactly.")


41.8015332773
36.1356109666
31.8349723083
28.4097472647
25.6079537436
23.2719778825
21.2952879314
19.6025083055
18.1380210539
16.860354506
15.7375756925
14.7444202091
13.8608667614
13.0705635007
12.3602672885
11.7190174127
11.1378013291
10.6090322185
10.1262805657
9.68412714536
9.27788466751
8.90363074088
8.5578880435
8.23773474246
7.94050799109
7.66398492906
7.40616130104
7.16522352798
6.93963549332
6.72802806945
6.52918427647
6.34203817683
6.16562151638
5.9990795843
5.84164106616
5.69263361085
5.55142879184
5.41742960801
5.29010989821
5.1690428391
5.05380187923
4.94394280411
4.83910960415
4.73897568071
4.64324105842
4.55164912483
4.46397182517
4.37990761607
4.29932062391
4.22199452734
4.1477817207
4.0765418934
4.00803220737
3.94211069979
3.87862962981
3.81744608633
3.75844794653
3.70152898905
3.64652184943
3.59330925233
3.5418655805
3.49213246651
3.44401736912
3.39743866911
3.35232887738
3.30862717267
3.26626762491
3.22521568035
3.18536608843
3.14673057249
